//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pontosnotaveis.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbcptmEntities : DbContext
    {
        public dbcptmEntities()
            : base("name=dbcptmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<conexao> conexao { get; set; }
        public virtual DbSet<estacao> estacao { get; set; }
        public virtual DbSet<linha> linha { get; set; }
        public virtual DbSet<pontosnotaveis> pontosnotaveis { get; set; }
        public virtual DbSet<tipodeelemento> tipodeelemento { get; set; }
    }
}
