//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pontosnotaveis.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class pontosnotaveis
    {
        public int id { get; set; }
        public Nullable<int> idlinha { get; set; }
        public Nullable<int> idestacao { get; set; }
        public Nullable<int> idtipodeelemento { get; set; }
        public Nullable<int> via { get; set; }
        public string especificacoes { get; set; }
        public Nullable<decimal> localkm { get; set; }
    
        public virtual estacao estacao { get; set; }
        public virtual linha linha { get; set; }
        public virtual tipodeelemento tipodeelemento { get; set; }
    }
}
