//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composicao
    {
        public int id { get; set; }
        public int id_Produto { get; set; }
        public decimal fracao { get; set; }
        public Nullable<int> id_item_pedido { get; set; }
    
        public virtual Itens Itens { get; set; }
        public virtual Produtos Produtos { get; set; }
    }
}
