//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estacas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public long ID { get; set; }
        public long ID_Projects_Piles { get; set; }
        public decimal Z { get; set; }
        public decimal H { get; set; }
        public decimal N72 { get; set; }
        public long ID_K { get; set; }
        public long ID_α { get; set; }
        public decimal Ap { get; set; }
        public decimal Ep { get; set; }
        public decimal Rp { get; set; }
        public decimal Al { get; set; }
        public decimal El { get; set; }
        public decimal Rl { get; set; }
        public decimal C_Rl { get; set; }
        public decimal Rt { get; set; }
        public decimal Distance { get; set; }
        public bool flactive { get; set; }
        public System.DateTime dateUpdate { get; set; }
        public System.DateTime dateCriation { get; set; }
        public bool fldelete { get; set; }
    
        public virtual Answer Answer1 { get; set; }
        public virtual Answer Answer2 { get; set; }
        public virtual Table_Items Table_Items { get; set; }
        public virtual Table_Items Table_Items1 { get; set; }
    }
}
