//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estacas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbent : DbContext
    {
        public dbent()
            : base("name=dbent")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answer { get; set; }
        public virtual DbSet<Pillar> Pillar { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<Projects_Piles> Projects_Piles { get; set; }
        public virtual DbSet<Table_Items> Table_Items { get; set; }
        public virtual DbSet<Tables> Tables { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
