//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estacas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pillar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pillar()
        {
            this.Projects_Piles = new HashSet<Projects_Piles>();
        }
    
        public long ID { get; set; }
        public string Code { get; set; }
        public decimal Length { get; set; }
        public decimal Width { get; set; }
        public decimal Charge { get; set; }
        public bool DistanceCurrency { get; set; }
        public bool flactive { get; set; }
        public System.DateTime dateUpdate { get; set; }
        public System.DateTime dateCriation { get; set; }
        public bool fldelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projects_Piles> Projects_Piles { get; set; }
    }
}
