//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estacas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects_Piles
    {
        public long ID { get; set; }
        public long ID_Stake { get; set; }
        public string code { get; set; }
        public bool flcurrency { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public bool flactive { get; set; }
        public System.DateTime dateUpdate { get; set; }
        public System.DateTime dateCriation { get; set; }
        public bool fldelete { get; set; }
        public long ID_Projects { get; set; }
        public long ID_Pilar { get; set; }
    
        public virtual Table_Items Table_Items { get; set; }
        public virtual Pillar Pillar { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
