//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComprasWeb.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDOS
    {
        public long ID_PEDIDO { get; set; }
        public long ID_CLIENTE { get; set; }
        public string VALOR { get; set; }
        public long N_PEDIDO { get; set; }
        public long ID_PRODUTO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual PRODUTO PRODUTO { get; set; }
    }
}
