//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComprasWeb.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELACAO_LOJA_PRODUTO
    {
        public long ID_RELACAO_LOJA_PRODUTO { get; set; }
        public long ID_LOJA { get; set; }
        public long ID_PRODUTO { get; set; }
        public Nullable<long> ESTOQUE { get; set; }
    
        public virtual LOJA LOJA { get; set; }
        public virtual PRODUTO PRODUTO { get; set; }
    }
}
