//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locadora_Carros.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbempresasparaisoEntities : DbContext
    {
        public dbempresasparaisoEntities()
            : base("name=dbempresasparaisoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tabela_Fabricantes> Tabela_Fabricantes { get; set; }
        public virtual DbSet<Tabela_Modelos> Tabela_Modelos { get; set; }
        public virtual DbSet<Tabela_Usuario> Tabela_Usuario { get; set; }
        public virtual DbSet<Tabela_Veiculos> Tabela_Veiculos { get; set; }
        public virtual DbSet<Tabela_Usuario_Veiculo> Tabela_Usuario_Veiculo { get; set; }
    }
}
