//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locadora_Carros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabela_Modelos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tabela_Modelos()
        {
            this.Tabela_Veiculos = new HashSet<Tabela_Veiculos>();
        }
    
        public int ID { get; set; }
        public string Modelo { get; set; }
        public Nullable<int> ID_Fabricante { get; set; }
    
        public virtual Tabela_Fabricantes Tabela_Fabricantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tabela_Veiculos> Tabela_Veiculos { get; set; }
    }
}
